export const studyMeta = {
  title: 'Initiation Visit Report',
  version: 'Version 18.0',
  formDocNumber: 'TMP-0010246',
  parentDocNumber: 'SOP-0066820',
  sponsor: 'AstraZeneca',
};

export const headerFields = [
  { id: 'studyCode',      label: 'Study Code',                      value: 'Eliminate-2 (D7261C00005)' },
  { id: 'siteNumber',     label: 'Study Site Number',                value: '' },
  { id: 'pi',             label: 'Principal Investigator',           value: '' },
  { id: 'siteAddress',    label: 'Study Site Address',               value: '' },
  { id: 'monitorName',    label: 'Monitor Name',                     value: '' },
  { id: 'visitDates',     label: 'Visit Date(s)',                    value: '' },
  { id: 'visitFormat',    label: 'Visit Conducted',                  value: 'In Person' },
  { id: 'remoteReason',   label: 'Reason for remote (if applicable)',value: '' },
  { id: 'eventReviewed',  label: 'Monitoring Event Reviewed?',       value: 'Yes' },
  { id: 'reviewedBy',     label: 'Reviewed By',                      value: '' },
  { id: 'reviewDate',     label: 'Date Review Completed',            value: '' },
  { id: 'reportAuthor',   label: 'Report Author',                    value: '' },
  { id: 'reportStatus',   label: 'Report Status',                    value: 'Draft' },
];

export const personnelRows = [
  { name: '', role: 'Principal Investigator (PI)', present: 'Y' },
  { name: '', role: 'Sub-Investigator (Sub-I)',    present: 'Y' },
  { name: '', role: 'Study Coordinator (SC)',       present: 'Y' },
  { name: '', role: 'Study Nurse',                  present: '' },
  { name: '', role: 'MSLM',                         present: '' },
  { name: '', role: 'LSAD',                         present: '' },
  { name: '', role: 'Lead-CRA',                     present: '' },
  { name: '', role: 'Other',                         present: '' },
];

export const sections = [
  {
    id: '1',
    title: 'Training of Study Personnel',
    preamble: 'Was training provided to the study site regarding the following:',
    questions: [
      { id: '1.1',  expected: 'Yes', answer: 'Yes', text: 'Study rationale and objectives?',
        comment: 'The objective of this "pre-approval" Site Initiation Visit was conducted for training purposes only AND no patient-related procedures were / will be performed, and the site was clearly instructed that recruitment can only begin after IEC approval and full site activation via ready to enrolment. After this Visit the site is fully prepared to conduct the study in compliance with the Clinical Study Protocol Version xx, ICH-GCP, and applicable regulations. The visit included training on study procedures, systems, and safety reporting requirements.' },
      { id: '1.2',  expected: 'Yes', answer: 'Yes', text: 'Clinical Study Protocol requirements, including adherence thereto?',
        comment: 'Training was provided according to SIV PPT V.x.x. dated YYYY MMM DD and CSP V.X.X. dated YYYY MMM DD.' },
      { id: '1.3',  expected: 'Yes', answer: 'Yes', text: 'Key elements of the Investigator\'s Brochure?',
        comment: 'MSLM/CRA/LSAD discussed these with the PI/SI/SC according to the IB External Version/Addendum V.x.' },
      { id: '1.4',  expected: 'Yes', answer: 'Yes', text: 'Study timelines?',
        comment: 'PI/SI stated that they planned to enroll 14 patients in summary as discussed during the SQV and confirmed during this SIV. PI will start with first screening/randomization planned for YYYY MM DD/Month.' },
      { id: '1.5',  expected: 'Yes', answer: 'Yes', text: 'Study assessments and visit schedule?',
        comment: 'CRA discussed with the site the study assessment and the visit schedule in detail according to CSP V x.x.' },
      { id: '1.6',  expected: 'Yes', answer: 'Yes', text: 'Procedures for screening, enrolment, randomisation and premature discontinuation?',
        comment: 'CRA discussed with the site the study assessment and the visit schedule in detail according to CSP V x.x.' },
      { id: '1.7',  expected: 'Yes', answer: 'Yes', text: 'Inclusion/exclusion criteria?',
        comment: 'CRA discussed with the site the study assessment and the visit schedule in detail according to CSP V x.x.' },
      { id: '1.8',  expected: 'Yes', answer: 'Yes', text: 'Subject information and consent requirements, including consent for biological samples/genetic testing, etc.?',
        comment: 'CRA discussed in detail according to CSP V x.x. Please also refer to 1.1 regarding the "Pre-Approval" nature of this visit.' },
      { id: '1.9',  expected: 'Yes', answer: 'Yes', text: 'Adverse Event reporting?',
        comment: 'CRA discussed with the site the AE reporting procedures in detail according to CSP V x.x.' },
      { id: '1.10', expected: 'Yes', answer: 'Yes', text: 'Serious Adverse Event (SAE) — reporting and follow up process? Importance of providing causality in SAE report?',
        comment: 'CRA discussed with the site the study assessment and the visit schedule in detail according to CSP V x.x.' },
      { id: '1.11', expected: 'Yes', answer: 'Yes', text: 'Pregnancy, Overdose, Medication Error, Drug Misuse & Abuse procedures?',
        comment: 'CRA discussed with the site the study assessment and the visit schedule in detail according to CSP V x.x. It was discussed in detail that there is HIGH risk for theft and that in that case the Site Monitor need to be notified immediately, no later than 24 hours.' },
      { id: '1.12', expected: 'Yes', answer: 'Yes', text: 'Doses and study drug regimens including disallowed and concomitant medication (pre-study and during the study), if applicable?',
        comment: 'MSLM, CRA, LSAD discussed in detail and site is in agreement.' },
      { id: '1.13', expected: 'Yes', answer: 'Yes', text: 'Procedures for study drug handling (ordering, receipt, storage, dispensing, return, accountability and destruction)?',
        comment: 'MSLM, CRA, LSAD discussed in detail and site is in agreement. Please also refer to 1.1 regarding the "Pre-Approval" nature of this visit.' },
      { id: '1.14', expected: 'Yes/NA', answer: 'NA', text: 'Emergency unblinding procedures, if applicable?',
        comment: 'NA — This study is open label.' },
      { id: '1.14.1', expected: 'Yes/NA', answer: 'NA', text: 'Has the PI delegated a Sub-I (or other medically qualified personnel) to the task of Emergency Unblinding on the Site Signature and Delegation of Responsibilities Log?',
        comment: 'NA — This study is open label.' },
      { id: '1.15', expected: 'Yes', answer: 'Yes', text: 'Requirements for the content of medical records?',
        comment: 'CRA discussed in detail, site is in agreement, e.g. for cross-checks, print-outs.' },
      { id: '1.16', expected: 'Yes', answer: 'Yes', text: 'Procedures and equipment required for sample collection, processing, labelling, storage, tracking and shipping, including timing?',
        comment: 'CRA discussed with the site in detail.' },
      { id: '1.17', expected: 'Yes/NA', answer: 'NA', text: 'Requirements for risk samples, if applicable?',
        comment: 'NA.' },
      { id: '1.18', expected: 'Yes', answer: 'Yes', text: 'Equipment including maintenance and calibration?',
        comment: 'All Certificates and calibrations are in place at site and were reviewed.' },
      { id: '1.19', expected: 'Yes', answer: 'Yes', text: 'Data recording (paper/electronic CRF), data query requirements, timelines and procedures?',
        comment: 'Site is fully trained and the accesses are working / were requested / will be requested accordingly.' },
      { id: '1.20', expected: 'Yes', answer: 'Yes', text: 'Obligation to inform the sponsor (through the Site Monitor) if Investigator has applied any urgent safety measures?',
        comment: 'Immediately notify Study Clinical Lead and Clinical Team representatives of Urgent Safety Measures taken by Investigator to relieve an immediate hazard to the study participant.' },
      { id: '1.21', expected: 'Yes', answer: 'Yes', text: 'Obligation to report to the Sponsor all non-compliance with the protocol and other applicable regulations and laws, e.g. serious breach?',
        comment: 'MSLM, CRA, LSAD discussed in detail and site is in agreement.' },
      { id: '1.22', expected: 'Yes', answer: 'Yes', text: 'Comments regarding Training of Study Site Personnel.',
        comment: 'The listed Personnel was fully trained. Furthermore the following points/documents were also discussed: Main ICF Vx, dated YYYY MM DD; Optional Genomic Research ICF Vx, dated YYYY MM DD; Future Research ICF Vx, dated YYYY MM DD; Pregnant Partner ICF Vx, dated YYYY MM DD. IP Handling (PharmaQL Manual Vx, dated YYYY MM DD), Biological Sample Handling, Recruitment and Retention and ISF. Vendors: iMediData (RAVE), Signant Health (IRT), Temperature control (MonTE), Teckro, Event Adjudication (JUDI), Central Laboratory (IOVIA). Tablet questionnaires: PRO (Signant Health) and eCOA. The study team was informed that study team members who were not participating in the SIV must be trained according to their role in the study before he or she can participate in the study.' },
    ],
  },
  {
    id: '2',
    title: 'Subject Requirements and Procedures',
    questions: [
      { id: '2.1', expected: 'Yes', answer: 'Yes', text: 'Were the number of subjects (overall and per site) discussed with the site?',
        comment: 'The PI confirmed to recruit 14 patients in summary and will start with first screening/randomization planned for YYYY MM DD/Month. PI states he/she would like to randomize X patients per month.' },
      { id: '2.2', expected: 'Yes/NA', answer: 'Yes', text: 'Were the advertisements for subject recruitment (if applicable) discussed with the site?',
        comment: 'Please also refer to 1.1 regarding the "Pre-Approval" nature of this visit.' },
      { id: '2.3', expected: 'Yes', answer: 'Yes', text: 'Were materials (Thank You cards, Ongoing Communications during the study and Trial Results Summaries/Unblinding Communication cards after study completion) discussed and committed to by PI?',
        comment: 'CRA, LSAD discussed that in detail, also regarding the patient-reimbursement. Patient retention was discussed in detail and site is in agreement. CRA discussed in detail the Thank You Cards in German language and the site will distribute these to the patients.' },
    ],
  },
  {
    id: '3',
    title: 'IRB/IEC and Regulatory Authority Responsibilities',
    questions: [
      { id: '3.1', expected: 'Yes', answer: 'Yes', text: 'Were responsibilities for obtaining approval for updated CSP, ICFs and patient facing material as required per regulation, prior to implementation, discussed?',
        comment: 'The Site was informed that no study specific patient procedure should be performed prior to sponsor approval, that will be provided to the site via "Ready To Enrollment".' },
      { id: '3.2', expected: 'Yes/NA', answer: 'NA', text: 'Were responsibilities for reporting ISIs, other safety information and progress reports to the site IRB/IEC, Regulatory Authority, discussed, if applicable?',
        comment: 'NA — Sponsor will report these accordingly and inform the sites.' },
      { id: '3.3', expected: 'Yes', answer: 'Yes', text: 'Comments regarding IRB/IEC and Regulatory Authority Responsibilities.',
        comment: 'Please refer to 3.2.' },
    ],
  },
  {
    id: '4',
    title: 'Monitoring and Source Data Verification',
    questions: [
      { id: '4.1', expected: 'Yes', answer: 'Yes', text: 'Were remote monitoring visits discussed with Investigator? Is it agreed who (site staff) will be the key contact for these visits?',
        comment: 'CRA discussed in detail that REMs will regularly be conducted. The main SC will be the contact; medical queries will be forwarded or directly discussed with the PI/SI.' },
      { id: '4.2', expected: 'Yes', answer: 'Yes', text: 'Are Investigators aware they are expected to contact monitor before or at time of enrolment of first subject to discuss eligibility?',
        comment: 'Site is aware about first RMV after first patient was screened.' },
      { id: '4.3', expected: 'Yes', answer: 'Yes', text: 'Were on-site monitoring procedures (i.e., access to phone/fax/copiers; work area, agenda) and frequency of monitoring visits discussed?',
        comment: 'CRA discussed the frequency and site is in agreement.' },
      { id: '4.4', expected: 'Yes', answer: 'Yes', text: 'Were remote monitoring procedures as well as centralized monitoring (as applicable) discussed?',
        comment: 'CRA discussed in detail. Site is in agreement.' },
      { id: '4.5', expected: 'Yes', answer: 'Yes', text: 'Were SDV requirements and access to original records discussed? [Confirm in comments section if source documents are paper or if EMR will be used]',
        comment: 'The site is using printouts/EMR and the CRA will get access according to 21 CFR Part 11.' },
      { id: '4.6', expected: 'Yes/NA', answer: 'Yes', text: 'If EMR is used, is it confirmed if CRA will have local (on-site) EMR access or remote EMR access?',
        comment: 'CRA will get access only to study patients according to 21 CFR Part 11.' },
      { id: '4.7', expected: 'Yes/NA', answer: 'NA', text: 'Are Local Laboratory reference ranges available and up to date?',
        comment: 'NA — The site is using local lab for quick check, but Central Lab will be used in general.' },
      { id: '4.8', expected: 'Yes', answer: 'Yes', text: 'Comments regarding Monitoring and Source Data Verification.',
        comment: 'CRA discussed in detail that all applicable study patient data need to be reviewed on an ongoing basis. Site is in agreement.' },
    ],
  },
  {
    id: '5',
    title: 'Study Drug',
    questions: [
      { id: '5.1', expected: 'Yes', answer: 'Yes', text: 'Is the study drug storage facility considered adequate (security, temperature)?',
        comment: 'CRA checked the facility and considered it adequate.' },
      { id: '5.2', expected: 'Yes', answer: 'Yes', text: 'Comments regarding Study Drug.',
        comment: 'Please refer to 1.1 and site was informed regarding the IP restrictions, that were already communicated by LSAD to the site via email as confirmed. Initial IP Shipment will be initiated once activities for IP Greenlight are completed by site and sponsor. Site was instructed to inform LST prior any new patient screening/randomization due to IP restrictions that were communicated already to the sites. LST will check and confirm if the new patient screening/randomization will be approved.' },
    ],
  },
  {
    id: '6',
    title: 'Human Biological Samples',
    questions: [
      { id: '6.1', expected: 'Yes', answer: 'Yes', text: 'Is there an appropriate (security, temperature) storage area for samples?',
        comment: 'CRA checked during the SIV. Lab Samples will be stored accordingly in a secured fridge/freezer at -20°C and/or -80°C.' },
      { id: '6.2', expected: 'Yes/NA', answer: 'Yes', text: 'Have the required accreditation(s)/licenses been collected?',
        comment: 'CRA checked these during the SIV.' },
      { id: '6.3', expected: 'Yes/NA', answer: 'NA', text: 'Comments regarding Human Biological Samples.',
        comment: 'NA — Central Lab will be used. Main SC is IATA trained and will be responsible to prepare and organize the Lab Sample Shipment accordingly. The HbS Log provided by AstraZeneca Vx, dated YYYY MMM DD, will be used, or alternatively the site may use its own HbS Log template. The CRA informed the site that, at a minimum, all information required in the AZ HbS Log must be documented.' },
    ],
  },
  {
    id: '7',
    title: 'Web-based Data Capture / Randomization and Trial Supply Management (RTSM, IRT, IxRS)',
    questions: [
      { id: '7.1', expected: 'Yes', answer: 'Yes', text: 'Is the set-up of Web-based Data Capture (WBDC), Randomization and Trial Supply Management (RTSM, IRT, IxRS) at the site complete?',
        comment: 'All accesses were provided to the site and the accesses are working. SC activated her access; PI/SI accesses are pending — accesses will be provided after the "Pre-Approval" SIV.' },
      { id: '7.2', expected: 'Yes', answer: 'Yes', text: 'Is WBDC, RTSM (IRT, IxRS) training for site personnel complete and is access confirmed and activated accordingly (user id/password or access token)?',
        comment: 'The whole Site Team is fully activated.' },
      { id: '7.3', expected: 'Yes', answer: 'Yes', text: 'Comments regarding Web-based Data Capture / Randomization and Trial Supply Management (RTSM, IRT, IxRS).',
        comment: 'WBDC and IRT systems were trained during SIV. IRT access is already active / pending for: [list]. RAVE access is already active / pending for: [list].' },
    ],
  },
  {
    id: '8',
    title: 'Electronic Patient Reported Outcome (ePRO)',
    questions: [
      { id: '8.1', expected: 'Yes', answer: 'Yes', text: 'Is the ePRO storage facility considered adequate (space available for the devices and for charging the device batteries)?',
        comment: 'CRA checked and considered the facility adequate.' },
      { id: '8.2', expected: 'Yes', answer: 'Yes', text: 'Is ePRO training for site personnel complete and is access confirmed accordingly (user accounts/passwords)?',
        comment: 'The whole Site Team is fully activated. Account is active for: [list]. e-learning is required for: [list].' },
      { id: '8.3', expected: 'Yes', answer: 'Yes', text: 'Were contingency plans in the event of ePRO system failure and/or device malfunction discussed?',
        comment: 'CRA discussed the details with the site.' },
      { id: '8.4', expected: 'Yes', answer: 'Yes', text: 'Comments regarding Electronic Patient Reported Outcome.',
        comment: '' },
    ],
  },
  {
    id: '9',
    title: 'Study Materials and Supplies',
    questions: [
      { id: '9.1',  expected: 'Yes',    answer: 'Yes', text: 'Is an up-to-date Investigator Study File available and appropriately stored?',
        comment: 'CRA reviewed with the site the ISF and informed the site that after IEC Approval and "Ready To Enrollment" they will get provided the approved documents for filing in ISF.' },
      { id: '9.2',  expected: 'Yes/NA', answer: 'NA',  text: 'Is a signed Clinical Study Protocol available and appropriately stored?',
        comment: 'NA — It will be provided to the site after IEC Approval and the CSP PI Signature will be collected.' },
      { id: '9.3',  expected: 'Yes',    answer: 'Yes', text: 'Are signed Clinical Study Agreement and Source Data Agreement available and appropriately stored?',
        comment: 'CSA was fully executed and completed. SDA was collected during the SIV.' },
      { id: '9.4',  expected: 'Yes/NA', answer: 'NA',  text: 'Is a current Investigator Brochure available and appropriately stored?',
        comment: 'NA — It will be provided to the site after IEC Approval. Please refer to section 1.3.' },
      { id: '9.5',  expected: 'Yes/NA', answer: 'NA',  text: 'Are ePRO supplies and other relevant documentation (e.g. user instructions) available and appropriately stored?',
        comment: 'NA — It will be provided to the site after IEC Approval and the CSP PI Signature will be collected.' },
      { id: '9.6',  expected: 'Yes/NA', answer: 'NA',  text: 'Are Emergency unblinding tools available and appropriately stored (if applicable)?',
        comment: 'NA — Open label study.' },
      { id: '9.7',  expected: 'Yes/NA', answer: 'NA',  text: 'Are paper Case Report Forms available and appropriately stored (if applicable)?',
        comment: 'NA — Electronic CRF is used.' },
      { id: '9.8',  expected: 'Yes',    answer: 'Yes', text: 'Are subject diary cards, questionnaires and subject participation cards available, IRB/IEC-approved as required per regulation and appropriately stored?',
        comment: 'No — Patient material will be provided after site RtE.' },
      { id: '9.9',  expected: 'Yes/NA', answer: 'NA',  text: 'Are laboratory supplies available and appropriately stored?',
        comment: 'NA — will be provided after IEC Approval.' },
      { id: '9.10', expected: 'Yes/NA', answer: 'No',  text: 'Is Study Drug available and appropriately stored, if applicable?',
        comment: 'Study drug shipment will be triggered once site was activated in the IRT system.' },
      { id: '9.11', expected: 'Yes',    answer: 'Yes', text: 'Comments regarding Study Materials and Supplies.',
        comment: '' },
    ],
  },
  {
    id: '10',
    title: 'Other Study Requirements',
    questions: [
      { id: '10.1',  expected: 'Yes', answer: 'Yes', text: 'Were Clinical Study Agreement requirements and Source Data location discussed with the study site?',
        comment: 'CSA is completed. Source Data location was discussed with the site and site is in agreement that CRA will have access to all needed source data of study participants.' },
      { id: '10.2',  expected: 'Yes', answer: 'Yes', text: 'Does PI understand their responsibility to supervise any individual or party to whom they delegate study-related duties?',
        comment: 'PI is fully aware of his responsibility.' },
      { id: '10.3',  expected: 'Yes', answer: 'Yes', text: 'Was the delegation of responsibilities within the Study Site Team discussed with the study site?',
        comment: 'The DOR was completed during the SIV. Scan was collected and will be reviewed by LSAD and subsequently filed in eTMF.' },
      { id: '10.4',  expected: 'Yes', answer: 'Yes', text: 'Were Investigator Study File requirements and responsibilities discussed with the study site?',
        comment: '' },
      { id: '10.5',  expected: 'Yes', answer: 'Yes', text: 'Were archiving responsibilities discussed with the study site?',
        comment: 'Site archive will be X.' },
      { id: '10.6',  expected: 'Yes', answer: 'Yes', text: 'Were Financial Disclosure requirements discussed with the study site?',
        comment: 'FDFs were completed and collected from PI/SI names.' },
      { id: '10.7',  expected: 'Yes', answer: 'Yes', text: 'Were potential audit/inspection responsibilities discussed with the study site?',
        comment: 'Site is aware and will inform CRA/LSAD and Study Team as soon as they receive any notification regarding a site audit/inspection.' },
      { id: '10.8',  expected: 'Yes', answer: 'Yes', text: 'Was the study site provided with AstraZeneca (or study representative) contact information (who, how)?',
        comment: 'The ISF was reviewed during the SIV including the contact information of the AZ contact information.' },
      { id: '10.9',  expected: 'Yes', answer: 'Yes', text: 'Was the study site provided with the WBDC IS Service Desk contact information?',
        comment: '' },
      { id: '10.10', expected: 'Yes', answer: 'Yes', text: 'Was the study site provided with ePRO Service Provider Helpdesk and applicable contact information, if applicable?',
        comment: '' },
      { id: '10.11', expected: 'Yes', answer: 'Yes', text: 'Was the Sponsor obligation to provide Investigator with new Safety Information related to Investigational Product discussed?',
        comment: 'New safety information will be provided via Veeva Site Connect to PI, SI. PI and SI need to read and acknowledge electronically.' },
      { id: '10.12', expected: 'Yes', answer: 'Yes', text: 'If there are any other digital or electronic tools used in the study, have they been discussed? Note: If so, reference those tools in Comments.',
        comment: 'PI (and Sub-I) already has an active Veeva Site Connect account. Tools discussed: MonTE for IMP temperature tracking for shipments and storage condition deviations; Signant Health; IRT & eCOA/ePRO; iMediData Rave EDC; IOVIA Central Lab; ICON Adjudication; Teckro App for Study documents.' },
      { id: '10.13', expected: 'Yes', answer: 'Yes', text: 'Comments regarding Other Study Requirements.',
        comment: '' },
    ],
  },
];

export const issueLogColumns = [
  'Issue No.', 'Subject ID', 'Category', 'Summary', 'Created By', 'Status',
  'Issue Description', 'Action Description', 'Action Due Date',
];

export const observationLogColumns = [
  'Obs No.', 'Priority', 'Date Identified', 'Summary', 'Description',
  'Created By', 'Status', 'Actions Description', 'Actions Due Date',
  'Updates', 'Actual Completion Date',
];

export const resolvedColumns = [
  'Issue No.', 'Violation/Deviation Type', 'Subject ID', 'Category',
  'Summary', 'Created By', 'Status', 'Description', 'Action Description', 'Action Due Date',
];

export const followUpColumns = [
  'Action Item', 'Responsible Party', 'Status',
  'Date Identified', 'Date Resolved', 'Comments',
];
